version: '3.7'

services:
  springboot:
    build: .
    container_name: pjcobranza-spring
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql10.freesqldatabase.com:3306/sql10772773?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: sql10772773
      SPRING_DATASOURCE_PASSWORD: 8TaLhVTtiK
    ports:
      - "8092:8080"
    mem_limit: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
