version: '3.7'

services:
  springboot:
    build: .
    container_name: pjcobranza-spring
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql.freedb.tech:3306/freedb_pjCobranza?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: freedb_rkSam
      SPRING_DATASOURCE_PASSWORD: VR@%hZvzQ5%sqBg
    ports:
      - "8092:8080"
    mem_limit: 512m
