version: '3'
services:
  springboot:
    build: .
    container_name: pjcobranza-spring
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql105.infinityfree.com:3306/if0_38689568_pjcobranza?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: if0_38689568
      SPRING_DATASOURCE_PASSWORD: blXQhYNQkPVf
    ports:
      - "8092:8080"
    mem_limit: 512m
