spring:
  application:
    name: PjCobranza-Back

  datasource:
    url: jdbc:mysql://sql10.freesqldatabase.com:3306/sql10772773?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: sql10772773
    password: 8TaLhVTtiK
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
